const bootstrapModal = require('./bootstrap-modal');
const ddevShell = require('./ddev-shell');

/**
 * Updates describe modal content with current site data and shows modal
 * @param title
 * @param body
 */
function showDescribeModal(title, body) {
  $('#describeModal .modal-title').text(title);
  $('#describeModal .modal-body').html(body);
  $('#describeModal').modal();
}

/**
 * TEMPLATE - generates markup for the site details modal
 * @param details {object} - site details object generated by ddevShell.describe
 * @returns {string} - markup for site details modal
 */
function createDetails(details) {
  let output = '';
  for (const key in details) {
    if (details.hasOwnProperty(key)) {
      const section = details[key];
      output += `<div><h3>${key}</h3><table>`;
      for (const k in section) {
        if (section.hasOwnProperty(k) && k !== 'notes') {
          output += `<tr><td>${k}</td>` + `<td>${section[k]}</td></tr>`;
        }
      }
      output += '</table>';
      if (section.notes) {
        output += '<ul>';
        section.notes.forEach(note => {
          output += `<li>${note}</li>`;
        });
        output += '</ul>';
      }
      output += '</div>';
    }
  }
  return output;
}

/**
 * Initialization - hook UI and generate markup.
 */
function init() {
  $('body').append(bootstrapModal.createModal('describeModal', '', ''));
  $(document).on('click', '.infobtn', function() {
    console.log('describe');
    const siteName = $(this)
      .closest('.column')
      .data('sitename');
    ddevShell.describeModal(siteName).then(data => {
      showDescribeModal(`Additional Info For ${siteName}`, createDetails(data));
    });
  });
}

module.exports.init = init;
