version: 2
stages:
  build:
    machine: true

#    environment:
#      GOPATH: /home/circleci/go
    working_directory: ~/ddev-ui

    steps:

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - apt-get -qq install wine wine-mono

      - checkout

      - run: make linux

